### ISSUE TITLE
Why do the functions have 'command' in the name?

### ISSUE THREAD

**Issue by juneb** [janegilring/PSVersionCompare#3]
Why are the functions called 

Compare-PSVersionCommand
Get-PSVersionCommand

instead of:

Compare-PSVersion
Get-PSVersion

?

**Comment by janegilring** [comment]
In order to indicate that commands is being compared. I`ve been thinking of adding functions for comparing other things, such as automatic variables (for example, Compare-PSVersionVariable).
Also, Get-PSVersion is the name of a function in the [PSVersion](https://github.com/janegilring/PSVersion/tree/master/Functions) module.

**Comment by juneb** [comment]
Ah. Understand. I'll close the issue.
